# Numpy

In [2]:
import numpy as np
np.__version__

'1.20.3'

In [4]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


# Array

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.empty(2)

array([0., 0.])

In [10]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [11]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

# Add, Remove, Sort

In [12]:
arr =  np.array([1,2,3,4,5,6,7,8])
print(arr)
np.append(arr, [1,2])

[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [13]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [15]:
arr = np.array([2, 1, 3, 5, 7, 4, 6, 8])
print (arr)
np.sort (arr)

[2 1 3 5 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

# Shape and Size

In [17]:
array_example = np.array([[[0, 1, 2, 2],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 2]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [18]:
array_example.size

24

In [19]:
array_example.shape

(3, 2, 4)

# Reshape

In [22]:
a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


# Convert 1D array to 2D array

In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [21]:
a2 = a[np.newaxis]
print(a2)
a2.shape

[[1 2 3 4 5 6]]


(1, 6)

In [23]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[0 1 2 3 4 5]]


(1, 6)

In [25]:
col_vector = a[:, np.newaxis]
print (col_vector)
col_vector.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [27]:
b = np.expand_dims(a, axis = 1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [28]:
c = np.expand_dims(a, axis = 0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

# Indexing and Slicing

In [29]:
data = np.array([1,2,3])

print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [31]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print (a)

# print semua value dalam array yang kurang dari 5
print(a[a<5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [32]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [33]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [34]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Exisiting Data

In [36]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [37]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])


# Vertikal
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [38]:
# horizontal
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [40]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [41]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# Membuat array baru yang melihat data yang sama
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
# Copy method
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [44]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [45]:
b = np.array([[1, 1], [2, 2]])
b

b.sum(axis=0)

array([3, 3])

In [46]:
b.sum(axis=1)

array([2, 4])

In [47]:
data = np.array([1,2])
data

array([1, 2])

In [48]:
ones = np.ones(2)
ones

array([1., 1.])

In [49]:
data + ones

array([2., 3.])

In [50]:
data * data

array([1, 4])

In [51]:
data / data

array([1., 1.])

# More array Operations

In [52]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [53]:
A.sum()

4.8595784

In [54]:
A.min()

0.05093587

In [55]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# Matrices

Creating Matrices

In [56]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.84987392 0.98166237]
 [0.01454588 0.59398583]
 [0.88325651 0.52758069]]


Matrix Arithmetic

In [57]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [58]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [59]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [60]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [61]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [62]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [63]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [64]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


# Matrix Aggregation

In [65]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [66]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [67]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [69]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [70]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [71]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [72]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [75]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [76]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [77]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [78]:
print(np.random.random((4,3,2)))

[[[0.27588461 0.84846052]
  [0.50670409 0.75127062]
  [0.33523235 0.27916654]]

 [[0.61642673 0.07298024]
  [0.95490682 0.61040623]
  [0.17668117 0.73456931]]

 [[0.46967454 0.94432905]
  [0.66602913 0.41709265]
  [0.6165975  0.11750904]]

 [[0.77938571 0.26936379]
  [0.68203958 0.75079863]
  [0.78834868 0.5793642 ]]]


# Flatten N-Dimensional Array

In [79]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [80]:
# use flatten to flatten array into 1D array
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Working with Math Formulas

In [81]:
a = np.random.rand(5)
print(a)

[0.88026141 0.25910316 0.44359238 0.64994577 0.75295066]


In [82]:
a.shape 

(5,)

In [83]:
print(a.T)

[0.88026141 0.25910316 0.44359238 0.64994577 0.75295066]


In [84]:
print(np.dot(a, a.T))

2.0281330037035623


In [86]:
a = np.random.rand(5,1)

In [87]:
print(a.T)

[[0.9845534  0.04568691 0.09375067 0.71271383 0.37595423]]


In [88]:
print(np.dot(a, a.T))

[[0.9693454  0.0449812  0.09230254 0.70170482 0.37014702]
 [0.0449812  0.00208729 0.00428318 0.03256169 0.01717619]
 [0.09230254 0.00428318 0.00878919 0.0668174  0.03524596]
 [0.70170482 0.03256169 0.0668174  0.507961   0.26794778]
 [0.37014702 0.01717619 0.03524596 0.26794778 0.14134159]]


In [89]:
a = np.random.rand(1,5)
print(a)

[[0.67317825 0.47288276 0.16842955 0.48369269 0.29857419]]


# TpisPy

In [90]:
a = np.random.rand(5)
print(a)

[0.57434    0.20637193 0.56143933 0.38079195 0.89396535]


In [91]:
print(a.T)

[0.57434    0.20637193 0.56143933 0.38079195 0.89396535]


In [92]:
print(np.dot(a, a.T))

1.6318464917922668


In [93]:
a = np.random.rand(1,5)
print(a)

[[0.43620029 0.50539916 0.91528705 0.27837435 0.42234597]]
