In [2]:
import numpy as np
import pandas as pd

In [5]:
a = int(input('mulai: '))
b = int(input('selesai: '))
c = int(input('banyak data: '))

data = np.random.randint(a,b,c)

mulai: 1
selesai: 61
banyak data: 28


In [11]:
# 1 Dimensi
data

array([22, 55, 31, 14, 47, 35, 51, 29,  8, 44, 41, 22, 11, 39, 10, 34,  9,
       41, 47, 46, 53, 59, 28, 37, 57, 14, 25,  9])

In [12]:
# Dua dimensi
twodim = data.reshape(4,7)
twodim

array([[22, 55, 31, 14, 47, 35, 51],
       [29,  8, 44, 41, 22, 11, 39],
       [10, 34,  9, 41, 47, 46, 53],
       [59, 28, 37, 57, 14, 25,  9]])

In [10]:
# Tukar posisi
twodim[::-1]

array([[59, 28, 37, 57, 14, 25,  9],
       [10, 34,  9, 41, 47, 46, 53],
       [29,  8, 44, 41, 22, 11, 39],
       [22, 55, 31, 14, 47, 35, 51]])